### ISSUE TITLE
*Question*

### ISSUE THREAD

**Issue by perfectOfFantasy** [melluh/minecraft-protocol-json#1]
Hey, could you publish your generator? (because you probably don't write it by hand haha) If you just don't want to publish this generator, it would be great if you could also publish lower versions (I mean all versions from 1.7.2 to the newest)

//edit
Personally, i wrote a simple extractor from wiki.vg, although i got stuck at stage of more complex tables (for example https://wiki.vg/Protocol#Player_Info)

**Comment by melluh** [comment]
I actually did write it by hand! I thought about writing a generator, but ultimately decided it'd probably be quicker to just spend a couple of hours looking at the source code and writing it myself. Also, packet changes between versions are often quite minor, so keeping it up to date once the initial work is done isn't too much work. However, writing definitions for all the older versions would be quite a long process, and not something I'm interested in doing (I made this mostly for my own purposes).
